### ISSUE TITLE
Volunteer Emails

### ISSUE THREAD

**Issue by laveur** [laveur/paw_apply#95]
Need Emails for the following states:

* [New](https://github.com/laveur/paw_apply/blob/master/templates/email-volunteers-confirm.html)
* Accepted
* ~~Waitlisted?~~
* Declined

**Comment by AntPhiSul** [comment]
**New:**

Hello "applicant"!

We appreciate your interest in volunteering for PacAnthro "Year".
We will review your application and get back to you shortly.


-Department
Contact Email



**Accepted:**

Congratulations! You are now part of the PacAnthro Team! We look forward to working with you to serve the community we all love!
Telegram Volunteer Group Link:

If you have any questions or comments you can reach out to "Contact Email"

-Department

**Denial:**

Thank you for your interest in volunteering at PacAnthro! Unfortunately your application was denied. If you are wanting to inquire regarding the reason for denial, please reach out to -Contact email-

-Department
